#!/bin/bash

HIDEME_FILEPATH="/config/${HIDEME_FILE}"

if [ -f "$HIDEME_FILEPATH" ]; then
	echo "$HIDEME_FILEPATH exist"
	chmod +x $HIDEME_FILEPATH
	chmod 777 $HIDEME_FILEPATH
else 
	echo "$HIDEME_FILEPATH does not exist, copy default"
	cp /hideme.yaml /config/hideme.yaml
	chmod +x /config/hideme.yaml
	chmod 777 /config/hideme.yaml
fi

CA_FILEPATH="/config/CA.pem"

if [ -f "$CA_FILEPATH" ]; then
	echo "$CA_FILEPATH exist"
	chmod +x $CA_FILEPATH
	chmod 777 $CA_FILEPATH
else 
	echo "$CA_FILEPATH does not exist, copy default"
	cp /CA.pem /config/CA.pem
	chmod +x /config/CA.pem
	chmod 777 /config/CA.pem
fi

### get access token if not exist

AT_FILEPATH="/config/accessToken.txt"

if [ -f "$AT_FILEPATH" ]; then
	echo "$AT_FILEPATH exist"
	chmod +x $AT_FILEPATH
	chmod 777 $AT_FILEPATH
else 
	echo "$AT_FILEPATH does not exist, creating new one"
	hide.client.linux -u ${HIDEME_USER} -P ${HIDEME_PASS} token ${HIDEME_SERVER}
	cp accessToken.txt "$AT_FILEPATH"
	chmod +x /config/accessToken.txt
	chmod 777 /config/accessToken.txt
fi

### start HideMe

hide.client.linux -4 -s ${LOCAL_NET} -u ${HIDEME_USER} -P ${HIDEME_PASS} -c /config/hideme.yaml connect ${HIDEME_SERVER}