#!/bin/bash

### remove old files if exists
if [ -f /config/hideme.yaml ]; then
  rm -f /config/hideme.yaml
fi
if [ -f /config/CA.pem ]; then
  rm -f /config/CA.pem
fi

### check if cert is in place
if [ -f "${CA_FILEPATH}" ]; then
  echo "${CA_FILEPATH} exist"
  chmod 777 ${CA_FILEPATH}
else 
  echo "${CA_FILEPATH} does not exist, copy default"
  cp /opt/defaults/CA.pem ${CA_FILEPATH}
  chmod 777 ${CA_FILEPATH}
fi

### display error if no user, password, server was specified
if [ -z "${HIDEME_USER}" ] || [ -z "${HIDEME_PASS}" ] || [ -z "${HIDEME_SERVER}" ] || [ -z "${LOCAL_NET}" ]; then
  echo "Error: One or more variables where not passed over!"
  echo "You have to specify: HIDEME_USER, HIDEME_PASS, HIDEME_SERVER & LOCAL_NET"
  sleep infinity
fi

### get access token if not exist
if [ -f "${AT_FILEPATH}" ]; then
  echo "${AT_FILEPATH} exist"
  chmod 777 ${AT_FILEPATH}
else 
  echo "${AT_FILEPATH} does not exist, creating new one"
  cd /config
  /usr/bin/hide.me -ca ${CA_FILEPATH} -u ${HIDEME_USER} -P ${HIDEME_PASS} token ${HIDEME_SERVER%%.*}
  chmod 777 /config/accessToken.txt
fi

### start HideMe

/usr/bin/hide.me -4 -s ${LOCAL_NET} -ca ${CA_FILEPATH} -t ${AT_FILEPATH} -u ${HIDEME_USER} -P ${HIDEME_PASS} ${START_PARAMS} connect ${HIDEME_SERVER%%.*}
