#!/bin/sh

### Start socks5
if [ ${HIDEME_SOCKS} == "off" ]; then
  echo "socks5 disabled"
  sleep infinity
else
  ### wait until hide.me connect is found
  while ! pgrep -af "/usr/bin/hide.me.*connect" >/dev/null; do
    sleep 5
  done
  sleep 3
  # start
  echo "socks5 started"
  socks5
fi
