#!/bin/sh

### Start microsocks
if [ ${HIDEME_SOCKS} == "off" ]; then
  echo "microsocks disabled"
  sleep infinity
else
  ### wait until hide.me connect is found
  while ! pgrep -af "/usr/bin/hide.me.*connect" >/dev/null; do
    sleep 5
  done
  sleep 3
  # start
  echo "microsocks started"
  microsocks
fi
